=pod

=head1 NAME

Google::Travel::Matrix - To access the Google Travel Matrix API .

=head1 VERSION

version 0.1

=head2 origins
       An address string,  or string of addresses. Each address element must
       be delimited by a comma. If more than one address, then seperate each
       address with a '|'. 
       An address HashRef of this format 
       {
        address_1 => $address_1,
        address_2 => $address_2,
        city => $city,
        state => $state, 
        country => $country,
        zip => $zip, 
        }
        ,  will be coerced to a valid address string. 

       An arrayref of address strings and or address HashRefs  will be coerced into a compatible address(s)
       string(s).

=head2 destinations
    The destination addresses. Follows the same formatting rules as 'origins'

=head2 process_results
 See what we need from the results.
 Note::
      Each Row corresponds to an origin.
      Each element within a row corresponds to a paring of the origin 
      with a destination value.

=head2 get_all_elements
 Get the distances.
 Create a hash with the address,  

=head3 _get_formatted_origins
    Returns the origins address array, formatted for the Google API

=head3 _get_formatted_destinations
    Reurns the destinations address array, formatted for the Google API

=head3 _matrix_query_params
    Build and returns all the params for the Google Travel Matrix request
    as a HashRef.
    Use the formatted origins and destinations address's.
    Omits the requested output format specifier.

=head2 _build_uri
   Build and return the query URI.

=head2 _call_google_api
   Call the google travel matrix API.
   Returns the Google response

=head2 _convert_from_json
   Convert the Google response from JSON.

=head2 _convert_from_xml
   Convert the Google response from XML to a Perl Data Structure;

=head2 
    Readonly => %valid_google_languages (
        ar => ARABIC,
        eu => BASQUE,
        bg => BULGARIAN,
        bn => BENGALI,
        ca => CATALAN,
        cs => CZECH,
        da => DANISH,
        de => GERMAN,
        el => GREEK,
        en => ENGLISH,
        en-AU => ENGLISH(AUSTRALIAN),
        en-GB => ENGLISH( GREAT BRITAIN ),
        es => SPANISH,
        eu => BASQUE,
        fa => FARSI,
        fi => FINNISH,
        fil => FILIPINO,
        fr => FRENCH,
        gl => GALICIAN,
        gu => GUJARATI,
        hi => HINDI,
        hr => CROATIAN,
        hu => HUNGARIAN,
        id => INDONESIAN,
        it => ITALIAN,
        iw => HEBREW,
        ja => JAPANESE,
        kn => KANNADA,
        ko => KOREAN,
        lt => LITHUANIAN,
        lv => LATVIAN,
        ml => MALAYALAM,
        mr => MARATHI,
        nl => DUTCH,
        nn => NORWEGIAN NYNORSK,
        no => NORWEGIAN,
        or => ORIYA,
        pl => POLISH,
        pt => PORTUGUESE,
        pt-BR => PORTUGUESE(BRAZIL),
        pt-PT => PORTUGUESE(PORTUGAL),
        rm => ROMANSCH,
        ro => ROMANIAN,
        ru => RUSSIAN,
        sk => SLOVAK,
        sl => SLOVENIAN,
        sr => SERBIAN,
        sv => SWEDISH,
        tl => TAGALOG,
        ta => TAMIL,
        te => TELUGU,
        th => THAI,
        tr => TURKISH,
        uk => UKRAINIAN,
        vi => VIETNAMESE,
        zh-CN => CHINESE(SIMPLIFIED),
        zh-TW => CHINESE(TRADITIONAL),
    );

=head1 AUTHOR

Austin Kenny <aibistin.cionnaith@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Austin Kenny.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

